version: "3"

services:
  db:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=newsportal
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=newsportal
    ports:
      - 5430:5432

  redis:
    image: redis:5-alpine
    ports:
      - 6378:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
    command: bash -c "python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8098:8000
    environment:
      - DB_HOST=db
      - DB_USER=newsportal
      - DB_PASS=12345
      - DB_PORT=5432
      - DB_NAME=newsportal
      - DEBUG=True
      - SECRET_KEY=%=m_%djfn#6c&ww+1&c5ofr73v1kg)^agrxk#95vuiw2c4)2)s

